### Python programming documentation

#### 1 Definition:

Python is a high-level, interpreted programming language that allows people to write computer programs. Python is famous for its clear, simple syntax, making it suitable for beginners and professionals to build websites, analyze data, make games, control robots, and more.

### 2 Variables and data types

A variable is a named place in memory where you can store data like numbers, text, or lists. Python figures out what type of data you are storing (int, float, str, etc.) just from the value you assign it 

Variables help you remember and reuse information, like saving a user's name or a calculation result.

In [13]:
x = 10
print(x) 

In [ ]:
y = 3.14
print(y)

In [ ]:
name = "Athahar"
print(name)

In [ ]:
fruits = ["apple", "banana", "cherry"]
print(fruits)

In [ ]:
coords = (10, 20)
print(coords)

In [ ]:
person = {"name": "Sam", "age": 25}
print(person)

In [ ]:
unique = {1, 2, 3}
print(unique)

In [ ]:
none_value = None
print(none_value)

In [ ]:
age = 18              
price = 19.99         
username = "Athahar"    
is_student = True 

we can check what dataype each variable is storing using type function

In [16]:
type(age)

int

In [18]:
type(price)

float

In [20]:
type(username)

str

In [22]:
type(is_student)

bool

### 3 Arithmetic Operators

### Definition:

Arithmetic operators are symbols that tell Python to perform math calculations like addition, subtraction, multiplication, division, and more.

They help you do calculations in your program, like adding numbers or finding results.

In [ ]:
a = 5 + 3
print(a)

In [ ]:
b = 10 - 4
print(b)

In [ ]:
c = 6 * 7
print(c)

In [ ]:
d = 20 / 5
print(d)

In [ ]:
e = 10 % 3
print(e)

In [ ]:
f = 2 ** 5
print(f)

In [ ]:
g = 15 // 2
print(g)

In [ ]:
h = (5 + 3) * 2
print(h)

In [ ]:
i = (8 - 2) / 3
print(i)

In [ ]:
j = (12 + 6) // 3
print(j)

In [27]:
a = 10 + 5
b = 10 - 3
c = 4 * 3
d = 20 / 4
e = 7 % 3
f = 2 ** 3

In [60]:
print("Addition: a = 10 + 5 =", a)
print("Subtraction: b = 10 - 3 =", b)
print("Multiplication: c = 4 * 3 =", c)
print("Division: d = 20 / 4 =", d)
print("Modulus (remainder): e = 7 % 3 =", e)
print("Exponentiation: f = 2 ** 3 =", f)


Addition: a = 10 + 5 = 15
Subtraction: b = 10 - 3 = 7
Multiplication: c = 4 * 3 = 12
Division: d = 20 / 4 = 5.0
Modulus (remainder): e = 7 % 3 = 1
Exponentiation: f = 2 ** 3 = 8


### 4 Comparison Operators

### Definition: 

Comparison operators (like ==, <, >, !=, <=, >=) are used to compare two values. Python checks the relationship and returns True or False.

To decide what happens next in your code based on conditions.

In [2]:
print(5 == 5)

True


In [4]:
print(7 != 3)

True


In [6]:
print(10 > 8)

True


In [ ]:
print(4 < 6)

In [ ]:
print(9 >= 9)

In [ ]:
print(12 <= 15)

In [ ]:
print("abc" == "abc")

In [ ]:
print(len("hi") == 2)

In [ ]:
print(3.5 > 2.1)

In [35]:
age = 16
print(age < 18)  
print(age == 18)  

True
False


### 5. Logical Operators 

### Definition:

Logical operators (and, or, not) connect multiple conditions to check if multiple things are true or false.

It is used for more complex decisions, like checking several things at once.

In [ ]:
print(5 > 3 and 10 > 2)

In [ ]:
print(4 < 2 or 9 > 1)

In [ ]:
print(not (5 == 5))

In [ ]:
print((7 > 4) and (3 < 10))

In [ ]:
print((2 == 3) or (10 > 4))

In [42]:
x = 10
y = 20
print(x > 5 and y < 30)  
print(x < 5 or y < 15)    
print(not x == 10)       

True
False
False


### 6 Conditional Statements

### Definition:

Conditional statements help programs make choices. Python mainly uses three: if, elif, and else. Here's each part explained in detail:

### a) if Statement:

### Definition:
An if statement checks if a condition is True. If it is, the code inside the if block runs. If not, the block is skipped. It's the basic tool for decision-making in Python.

It is used have the code do something only if a certain test or condition is met.

In [ ]:
x = 10
if x > 5:
    print("x is greater than 5")

### b) The elif Statement

### Definition:

elif is short for "else if". You use it to check a second (or third, or fourth, etc.) condition if the previous if condition(s) were False. It's a way to chain multiple choices together.

It is used when you have several possible options and you want to check them one by one.

In [50]:
marks = 80
if marks >= 90:
    print("Grade: A")
elif marks >= 75:
    print("Grade: B")
elif marks >= 60:
    print("Grade: C")

Grade: B


### c) The else Statement

### Definition

The else statement catches everything else that wasn't caught by the if or elif checks. You do not write a condition after else—it just runs if all the earlier tests fail.

It gives a default action or message when none of the above conditions are true.

In [10]:
num = -5
if num >= 0:
    print("Non-negative")
else:
    print("Negative")

Negative


In [12]:
y = 2
if y == 2:
    print("y equals 2")
else:
    print("y does not equal 2")

y equals 2


In [14]:
z = 12
if z < 5:
    print("Small")
elif z == 12:
    print("Exact")
else:
    print("Large")

Exact


In [16]:
marks = 85
if marks >= 90:
    print("A")
elif marks >= 80:
    print("B")
else:
    print("C")

B


In [18]:
score = 40
if score >= 90:
    print("Excellent!")
elif score >= 70:
    print("Good!")
else:
    print("Keep trying!")  

Keep trying!


In [58]:
temp = 15
if temp >= 30:
    print("It's hot outside")
elif temp >= 20:
    print("It's warm outside")
elif temp >= 10:
    print("It's cool outside")
else:
    print("It's cold outside")


It's cool outside


### 7. Loops

Loops repeat actions, saving you from writing the same code over and over. There are two main types: for and while.

### For Loop:

A for loop repeats code for each item in a list or range, one by one.

It is used to process every item in a group, or repeat an action a known number of times.

In [20]:
for i in range(5):
    print(i)

0
1
2
3
4


In [22]:
for char in "hello":
    print(char)

h
e
l
l
o


In [24]:
for num in [2, 4, 6]:
    print(num * 2)

4
8
12


In [26]:
for i in range(1, 6, 2):
    print(i)

1
3
5


In [28]:
for x in range(3):
    print("Athahar")

Athahar
Athahar
Athahar


In [ ]:
for i in range(10, 15):
    print(i)

In [ ]:
for index, val in enumerate(["a", "b", "c"]):
    print(index, val)

In [ ]:
for n in (1, 3, 5, 7):
    print(n**2)

In [ ]:
for line in ["one", "two"]:
    print(line.upper())

### While Loop

### Definition:
A while loop repeats code as long as a condition remains True.

It is used to keep doing something until a certain point (possibly unknown in advance).

In [30]:
i = 0
while i < 3:
    print(i)
    i += 1

0
1
2


In [32]:
count = 5
while count > 0:
    print(count)
    count -= 1

5
4
3
2
1


In [34]:
x = 1
while x <= 3:
    print(x * 2)
    x += 1

2
4
6


In [36]:
num = 10
while num >= 7:
    print(num)
    num -= 1

10
9
8
7


In [38]:
val = 0
while val < 10:
    print(val)
    val += 3

0
3
6
9


In [40]:
n = 1
while n < 5:
    print(n**2)
    n += 1

1
4
9
16


In [50]:
j = 0
while j < 4:
    print("Data")
    j += 1

Data
Data
Data
Data


In [48]:
word = "athahar"
i = 0
while i < len(word):
    print(word[i])
    i += 1

a
t
h
a
h
a
r


In [46]:
p = 5
while p >= 1:
    print(p * 10)
    p -= 1

50
40
30
20
10


In [ ]:
c = 0
while c != 3:
    print(c)
    c += 1


### 8 Object-Oriented Programming (OOPS)

### Definition:

Object-Oriented Programming (OOP) is a style of writing programs that brings code closer to the real world. In OOP, you design programs around objects—collections of data (attributes) and actions (methods) bundled together. This approach makes it easier to handle complex problems by grouping similar things and their behaviors.

OOP helps organize code, make programs easier to understand, and reuse code efficiently in large systems.

### a) Classes and Objects

### Class

#### Definition:

A class is like a blueprint or plan for making objects. It defines what data (attributes) and what actions (methods) objects of that kind will have.

To design various "types" of objects in your code, such as a Car, a Student, or a Book.

### Object

#### Definition:
An object is one specific thing created from a class blueprint. It can hold its own unique data.

Objects bring classes to life, turning a plan into something you can use and change.

### Attributes and Method

### Attributes Definition:
Attributes are pieces of information stored in an object—like a person's name or age.

To store important information about each object

In [52]:
class Dog:
    def bark(self):
        print("Woof")

d = Dog()
d.bark()

Woof


In [54]:
class Cat:
    def meow(self):
        print("Meow")

c = Cat()
c.meow()

Meow


In [ ]:
class Person:
    def __init__(self, name):
        self.name = name

p = Person("Athahar")
print(p.name)


In [56]:
class Book:
    def __init__(self, title):
        self.title = title

b = Book("Python documentation")
print(b.title)

Python documentation


In [58]:
class Car:
    def __init__(self, brand):
        self.brand = brand

car = Car("BMW")
print(car.brand)

BMW


In [60]:
class Student:
    def __init__(self, roll):
        self.roll = roll

s = Student(101)
print(s.roll)

101


In [62]:
class Laptop:
    def on(self):
        print("Laptop On")

l = Laptop()
l.on()

Laptop On


In [64]:
class Phone:
    def call(self):
        print("Calling")

ph = Phone()
ph.call()

Calling


In [66]:
class Teacher:
    def teach(self):
        print("Teaching")

t = Teacher()
t.teach()

Teaching


In [68]:
class Chair:
    def sit(self):
        print("Sitting")

ch = Chair()
ch.sit()

Sitting


In [87]:
class Car:
    def __init__(self, model):
        self.model = model

my_car = Car("Honda Civic")
print(my_car.model)

Honda Civic


### b) Attributes and Method

### Attributes Definition:
Attributes are pieces of information stored in an object—like a person's name or age.

To store important information about each object

In [ ]:
class Dog:
    def __init__(self, name):
        self.name = name
    def bark(self):
        print(self.name, "barks")
d = Dog("Max")
d.bark()

In [ ]:
class Circle:
    def __init__(self, r):
        self.radius = r
    def area(self):
        return 3.14 * self.radius * self.radius
c = Circle(5)
print(c.area())

In [ ]:
class Student:
    def __init__(self, name, marks):
        self.name = name
        self.marks = marks
    def info(self):
        print(self.name, self.marks)
s = Student("Alice", 90)
s.info()

In [ ]:
class Car:
    def __init__(self, brand, speed):
        self.brand = brand
        self.speed = speed
    def drive(self):
        print("Driving", self.brand, "at", self.speed)
c = Car("BMW", 120)
c.drive()

In [ ]:
class Phone:
    def __init__(self, model):
        self.model = model
    def call(self):
        print("Calling from", self.model)
p = Phone("iPhone")
p.call()

In [ ]:
class Lamp:
    def __init__(self, color):
        self.color = color
    def switch_on(self):
        print(self.color, "lamp is on")
l = Lamp("Red")
l.switch_on()

In [ ]:
class Teacher:
    def __init__(self, subject):
        self.subject = subject
    def teach(self):
        print("Teaching", self.subject)
t = Teacher("Math")
t.teach()

In [ ]:
class Laptop:
    def __init__(self, brand):
        self.brand = brand
    def start(self):
        print(self.brand, "laptop started")
l = Laptop("Dell")
l.start()

In [ ]:
class Fan:
    def __init__(self, blades):
        self.blades = blades
    def rotate(self):
        print("Rotating with", self.blades, "blades")
f = Fan(3)
f.rotate()

In [ ]:
class Box:
    def __init__(self, size):
        self.size = size
    def display(self):
        print("Box size:", self.size)
b = Box(10)
b.display()

### Methods Definition:

Methods are functions that belong to a class. They describe what objects can do.

Methods help objects perform tasks or change their information.

In [ ]:
class A:
    def hello(self):
        print("Hello")
obj = A()
obj.hello()

In [ ]:
class B:
    def add(self, a, b):
        return a + b
print(B().add(5, 7))

In [ ]:
class C:
    def square(self, n):
        return n * n
print(C().square(4))

In [ ]:
class D:
    def greet(self, name):
        print("Hi", name)
D().greet("Python Documentation")

In [ ]:
class E:
    def multiply(self, a, b, c):
        return a * b * c
print(E().multiply(2, 3, 4))

In [ ]:
class F:
    def upper(self, text):
        return text.upper()
print(F().upper("python"))

In [ ]:
class G:
    def reverse(self, text):
        return text[::-1]
print(G().reverse("hello"))

In [ ]:
class H:
    def concat(self, a, b):
        return str(a) + str(b)
print(H().concat("Py", "thon"))

In [ ]:
class I:
    def is_even(self, n):
        return n % 2 == 0
print(I().is_even(10))

In [ ]:
class J:
    def maximum(self, a, b):
        return a if a > b else b
print(J().maximum(8, 3))

###  Inheritance
#### Definition:
Inheritance lets you create a new class (child) that automatically gets the features of another class (parent). You can also add new features or change existing ones in the child class.

To avoid repeating code and to create a clear relationship between objects.

In [ ]:
class Animal:
    def speak(self):
        print("Some sound")
class Dog(Animal):
    pass
d = Dog()
d.speak()

In [ ]:
class Animal:
    def speak(self):
        print("Some sound")
class Cat(Animal):
    def speak(self):
        print("Meow")
c = Cat()
c.speak()

In [ ]:
class Person:
    def __init__(self, name):
        self.name = name
class Student(Person):
    def show(self):
        print(self.name)
s = Student("Alice")
s.show()

In [ ]:
class Vehicle:
    def __init__(self, brand):
        self.brand = brand
class Car(Vehicle):
    def __init__(self, brand, year):
        super().__init__(brand)
        self.year = year
c = Car("Toyota", 2022)
print(c.brand, c.year)

In [ ]:
class Writer:
    def write(self):
        print("Writing")
class Author(Writer):
    def write(self):
        print("Author writing")
    def publish(self):
        print("Published")
a = Author()
a.write()
a.publish()

In [ ]:
class A:
    def show_a(self):
        print("A")
class B(A):
    def show_b(self):
        print("B")
class C(B):
    def show_c(self):
        print("C")
obj = C()
obj.show_a()
obj.show_b()
obj.show_c()

In [ ]:
class Flyer:
    def move(self):
        print("Fly")
class Swimmer:
    def move(self):
        print("Swim")
class Duck(Flyer, Swimmer):
    pass
d = Duck()
d.move()

In [ ]:
class Base:
    def process(self):
        print("Base")
class Mid(Base):
    def process(self):
        super().process()
        print("Mid")
class Final(Mid):
    def process(self):
        super().process()
        print("Final")
f = Final()
f.process()

In [ ]:
class Shape:
    def info(self):
        print("Shape")
class Circle(Shape):
    def area(self, r):
        return 3.14 * r * r
class Square(Shape):
    def area(self, s):
        return s * s
c = Circle()
s = Square()
c.info()
print(c.area(3))
s.info()
print(s.area(4))

### d) Encapsulation

#### Definition:

Encapsulation is wrapping the data (attributes) and the methods (actions) together into one class and hiding the inner details from outside the class.

To protect data and prevent it from being changed by accident.

In [ ]:
class Account:
    def __init__(self, balance):
        self.__balance = balance
    def get_balance(self):
        return self.__balance
a = Account(100)
print(a.get_balance())

In [ ]:
class Data:
    def __init__(self):
        self.__val = 42
    def show(self):
        return self.__val
d = Data()
print(d.show())

In [ ]:
class Student:
    def __init__(self, name):
        self.__name = name
    def get_name(self):
        return self.__name
s = Student("Alice")
print(s.get_name())

In [ ]:
class Bank:
    def __init__(self, balance):
        self.__balance = balance
    def deposit(self, value):
        self.__balance += value
    def check(self):
        return self.__balance
b = Bank(200)
b.deposit(100)
print(b.check())

In [ ]:
class Box:
    def __init__(self, width):
        self.__width = width
    def get_width(self):
        return self.__width
box = Box(10)
print(box.get_width())

In [ ]:
class User:
    def __init__(self, password):
        self.__password = password
    def check(self, p):
        return self.__password == p
u = User("secret")
print(u.check("secret"))

In [ ]:
class Secret:
    def __init__(self):
        self.__text = "hidden"
    def reveal(self):
        return self.__text
s = Secret()
print(s.reveal())

In [ ]:
class Config:
    def __init__(self, setting):
        self.__setting = setting
    def read(self):
        return self.__setting
c = Config("dark mode")
print(c.read())

In [ ]:
class Number:
    def __init__(self, n):
        self.__n = n
    def get(self):
        return self.__n
num = Number(55)
print(num.get())

In [105]:
class Account:
    def __init__(self, balance):
        self.__balance = balance  

    def deposit(self, amount):
        self.__balance += amount

    def get_balance(self):
        return self.__balance

my_acc = Account(100)
my_acc.deposit(50)
print(my_acc.get_balance())   

150


### e) Polymorphism

#### Definition:
Polymorphism means "many forms." In Python, it lets you use the same method name in different classes and the correct version will be used for each object.


To write flexible code that can work with objects of different types.

In [ ]:
class Dog:
    def sound(self):
        print("Bark")
class Cat:
    def sound(self):
        print("Meow")
for pet in [Dog(), Cat()]:
    pet.sound()

In [ ]:
def add(a, b):
    return a + b
print(add(5, 6))
print(add("Py", "thon"))

In [ ]:
class Bird:
    def move(self):
        print("Fly")
class Fish:
    def move(self):
        print("Swim")
for obj in [Bird(), Fish()]:
    obj.move()

In [ ]:
class Shape:
    def area(self):
        pass
class Square(Shape):
    def area(self):
        return 4 * 4
class Circle(Shape):
    def area(self):
        return 3.14 * 3 * 3
print(Square().area())
print(Circle().area())

In [ ]:
class English:
    def greet(self):
        print("Hello")
class French:
    def greet(self):
        print("Bonjour")
for lang in [English(), French()]:
    lang.greet()

In [ ]:
class Parent:
    def speak(self):
        print("Parent")
class Child(Parent):
    def speak(self):
        print("Child")
Parent().speak()
Child().speak()

In [ ]:
class A:
    def calculate(self, a, b):
        return a + b
class B:
    def calculate(self, a, b):
        return a * b
print(A().calculate(4, 5))
print(B().calculate(4, 5))

In [ ]:
class Apple:
    def taste(self):
        print("Sweet")
class Lemon:
    def taste(self):
        print("Sour")
for fruit in [Apple(), Lemon()]:
    fruit.taste()

In [ ]:
class Pen:
    def write(self):
        print("Writing")
class Marker:
    def write(self):
        print("Drawing")
for tool in [Pen(), Marker()]:
    tool.write()

In [109]:
class Person:
    def __init__(self, name, age, profession):
        self.name = name
        self.age = age
        self.profession = profession

    def introduce(self):
        print(f"Hi, I'm {self.name}, {self.age} years old, and I work as a {self.profession}.")

    def celebrate_birthday(self):
        self.age += 1
        print(f"{self.name} just turned {self.age}!")


person1 = Person("Neha", 28, "Software Engineer")
person2 = Person("Raj", 34, "Doctor")

person1.introduce()      
person2.introduce()      
person1.celebrate_birthday()  


Hi, I'm Neha, 28 years old, and I work as a Software Engineer.
Hi, I'm Raj, 34 years old, and I work as a Doctor.
Neha just turned 29!


## Numpy and Pandas

## 1. What is NumPy?

NumPy (Numerical Python) is a powerful library in Python for working with numbers, especially arrays (tables of values). It provides incredibly fast ways to store, access, and do math on collections of numbers—much faster and more flexible than regular Python lists. NumPy forms the foundation for most scientific and data computing in Python.

**Uses**  
It makes handling big sets of numbers easy—like in statistics, engineering, or working with images. You can do calculations, reshaping, and complex mathematics all with just a few lines of code, and it's much faster than pure Python lists.


In [113]:
import numpy as np
arr = np.array([1, 2, 3, 4, 5])
print(arr)

[1 2 3 4 5]


## 2. NumPy Arrays

### a) Array Definition

A NumPy array is a grid or table of numbers, all stored together in memory. Unlike Python lists, NumPy arrays are typed (all numbers must be of the same type) and support fast mathematical operations.

**Uses**  
Arrays let you do things like adding, multiplying, or transforming entire groups of numbers instantly.


In [117]:
arr = np.array([10, 20, 30])
print(arr[1])  # Access second value: 20

20


### b)Creating Arrays

You can create arrays from Python lists, or generate special arrays (like zeros, ones, random numbers).

**Uses**  
To quickly build datasets and structures for computation.

In [125]:
zeros = np.zeros(3)         
ones = np.ones(5)           
rand = np.random.rand(4)   
print(zeros)
print(ones)
print(rand)

[0. 0. 0.]
[1. 1. 1. 1. 1.]
[0.48063187 0.21968775 0.32342814 0.34021448]


## c) Array Indexing and Slicing

Indexing lets you pick out specific numbers from an array. Slicing allows you to grab a part or chunk of an array.

**Uses**  
So you can examine, change, or analyze just certain rows or columns of data, like focusing on ages above 30.


In [130]:
arr = np.array([10, 20, 30, 40, 50])
print(arr[:3])   

[10 20 30]


## 4. Array Operations

NumPy allows you to do math directly on arrays—like adding a number to every value, multiplying two arrays together, or running calculations across all elements.

**Uses**  
It massively speeds up calculations—imagine adding 5 to every number in a million-value array in one go!

In [135]:
arr = np.array([1, 2, 3])
arr2 = np.array([10, 20, 30])
print(arr + arr2)        
print(arr * 2)           

[11 22 33]
[2 4 6]


## 5. Shape and Reshape

Shape describes how many rows and columns an array has. Reshape changes the layout into new dimensions (2D table, for example).

**Uses**  
To prepare data for analyses, convert between rows and columns, or organize for machine learning.

In [140]:
a = np.array([1, 2, 3, 4, 5, 6])
b = a.reshape((2, 3))      
print(b)

[[1 2 3]
 [4 5 6]]


## 6. Aggregate Functions (Sum, Mean, Max, Min)

Aggregate functions allow you to quickly summarize data—like getting the total sum, average (mean), biggest (max), or smallest (min) value in your array.

**Uses**  
These let you instantly understand or analyze your data set in useful ways.

In [147]:
arr = np.array([3, 7, 5])
print(np.sum(arr))  
print(np.mean(arr)) 
print(np.max(arr))   
print(np.min(arr))   

15
5.0
7
3


## 7. Broadcasting

Broadcasting lets NumPy automatically extend smaller arrays so operations can be performed without writing loops. For example, adding a single value to every element of a big array.

**Uses**  
It saves time and code when working with arrays of different shapes.

arr = np.array([1, 2, 3])
arr = arr + 5     
print(arr)
arr = np.array([1, 2, 3])
arr = arr + 5     
print(arr)

## 8. Multidimensional Arrays (Matrices)

NumPy can handle 2D or more-dimensional arrays, making it perfect for working with tables (matrices), images, or higher-dimensional data.

**Uses**  
For scientific data, images, machine learning, and statistical tables.

In [157]:
matrix = np.array([[1, 2], [3, 4]])
print(matrix[0, 1]) 

2


## 9. Saving and Loading Arrays

NumPy lets you save arrays to disk or load them again easily. This is useful when working with big data that you don’t want to recreate every time.

**Uses**  
For keeping and reusing work in long projects like analysis or machine learning.

In [168]:
arr = np.array([1, 2, 3])
np.save('my_array.npy', arr)     
new_arr = np.load('my_array.npy')
print(new_arr)

[1 2 3]


## Pandas

## 1. What is pandas?

pandas is a Python library made for handling and analyzing data, usually in table form (think Excel sheets, CSV files, or SQL tables). It makes it easy to load, change, clean, and summarize big sets of data—with just a few commands.

**Uses**  
pandas turns messy or raw data into something easy to understand and analyze. It’s the go-to tool for data science, research, business analysis, and any work with rows and columns.

In [262]:
import pandas as pd
data = pd.DataFrame({'name': ['Athahar', 'Sai'], 'score': [88, 77]})
print(data)

      name  score
0  Athahar     88
1      Sai     77


## 2. DataFrame and Series

### a) DataFrame

A DataFrame is pandas’ main table object—like a supercharged Excel spreadsheet, with rows and columns you can easily change or extract from.

**Uses**  
It helps you organize, clean, and analyze data from the real world (contacts, sales, experiment results).


In [265]:
df = pd.DataFrame({'City': ['Hyderabad', 'Bangalore'], 'Population': [8, 4]})
print(df)

        City  Population
0  Hyderabad           8
1  Bangalore           4


### b) Series

A Series is like a single column from a DataFrame—a list with labels.

**Uses**  
For handling just one set of data (like ages) or working with column-by-column operations.

In [268]:
ages = pd.Series([23, 35, 29])
print(ages)

0    23
1    35
2    29
dtype: int64


## 3. Reading and Writing Data

### a) Reading CSV Files

You can load data from CSV or Excel files (spreadsheets) directly into pandas for analysis.

**Uses**  
To quickly load real-world data into your code.

In [271]:
df = pd.read_csv("churn.csv")
df.head()

Call  Failure  Complains  Subscription  Length  Charge  Amount  \
0              8          0                    38               0   
1              0          0                    39               0   
2             10          0                    37               0   
3             10          0                    38               0   
4              3          0                    38               0   

   Seconds of Use  Frequency of use  Frequency of SMS  \
0            4370                71                 5   
1             318                 5                 7   
2            2453                60               359   
3            4198                66                 1   
4            2393                58                 2   

   Distinct Called Numbers  Age Group  Tariff Plan  Status  Age  \
0                       17          3            1       1   30   
1                        4          2            1       2   25   
2                       24          3            1       1   30   
3                       35          1            1       1   15   
4                       33          1            1       1   15   

   Customer Value  Churn  
0         197.640      0  
1          46.035      0  
2        1536.520      0  
3         240.020      0  
4         145.805      0

### b) Writing to CSV Files

Saves your processed data back to CSV, so you can share or reuse it.

**Uses**  
For saving results, exporting cleaned data, or sharing findings.

In [274]:
df.to_csv('results.csv', index=False)

## 4. Selecting Data

You can easily select specific rows or columns using labels or numbers—just like in a spreadsheet.

**Uses**  
To focus on interesting or important parts of your data.

In [277]:
print(df['Age'])         
print(df.iloc[0])     
[['Age', 'Status']]

0       30
1       25
2       30
3       15
4       15
        ..
3145    25
3146    55
3147    30
3148    30
3149    30
Name: Age, Length: 3150, dtype: int64
Call  Failure                 8.00
Complains                     0.00
Subscription  Length         38.00
Charge  Amount                0.00
Seconds of Use             4370.00
Frequency of use             71.00
Frequency of SMS              5.00
Distinct Called Numbers      17.00
Age Group                     3.00
Tariff Plan                   1.00
Status                        1.00
Age                          30.00
Customer Value              197.64
Churn                         0.00
Name: 0, dtype: float64


[['Age', 'Status']]

## 5. Filtering Data

Filtering means picking out only the rows or values that meet certain conditions.

**Uses**  
Find important data, like high scores or locations above a certain population.

In [280]:
aged_people = df[df['Age'] > 35]
aged_people

Call  Failure  Complains  Subscription  Length  Charge  Amount  \
20                7          0                    37               1   
23               21          1                    36               8   
30                3          0                    33               1   
31                0          1                    36               0   
32                0          0                    36               1   
...             ...        ...                   ...             ...   
3131              5          1                    38               0   
3132              5          0                    38               2   
3139              9          0                    28               1   
3141              5          0                    28               0   
3146             17          0                    17               1   

      Seconds of Use  Frequency of use  Frequency of SMS  \
20             11465               154                11   
23             10435                93                 1   
30              6785                97                14   
31               628                 7                 9   
32               338                 4                 4   
...              ...               ...               ...   
3131             933                13                16   
3132             643                10                11   
3139            1873                45                37   
3141            1130                16                28   
3146            9237               177                80   

      Distinct Called Numbers  Age Group  Tariff Plan  Status  Age  \
20                         47          4            1       1   45   
23                         42          5            2       1   55   
30                         22          5            1       1   55   
31                          4          4            1       2   45   
32                          2          5            1       1   55   
...                       ...        ...          ...     ...  ...   
3131                        6          4            1       2   45   
3132                        4          5            1       1   55   
3139                       70          5            1       1   55   
3141                        5          4            1       2   45   
3146                       42          5            1       1   55   

      Customer Value  Churn  
20           317.975      0  
23           159.420      0  
30           124.230      0  
31            38.375      1  
32            11.130      0  
...              ...    ...  
3131          63.650      1  
3132          26.295      0  
3139          84.270      0  
3141          98.650      0  
3146         261.210      0  

[565 rows x 14 columns]

## 6. Adding and Removing Columns

pandas lets you create new columns (from calculations) or remove columns you don’t need.

**Uses**  
To tidy up or add useful metrics to your dataset.

In [283]:
df["new_customer_value"] = df["Customer Value"]/2
df.head()

Call  Failure  Complains  Subscription  Length  Charge  Amount  \
0              8          0                    38               0   
1              0          0                    39               0   
2             10          0                    37               0   
3             10          0                    38               0   
4              3          0                    38               0   

   Seconds of Use  Frequency of use  Frequency of SMS  \
0            4370                71                 5   
1             318                 5                 7   
2            2453                60               359   
3            4198                66                 1   
4            2393                58                 2   

   Distinct Called Numbers  Age Group  Tariff Plan  Status  Age  \
0                       17          3            1       1   30   
1                        4          2            1       2   25   
2                       24          3            1       1   30   
3                       35          1            1       1   15   
4                       33          1            1       1   15   

   Customer Value  Churn  new_customer_value  
0         197.640      0             98.8200  
1          46.035      0             23.0175  
2        1536.520      0            768.2600  
3         240.020      0            120.0100  
4         145.805      0             72.9025

In [285]:
del df["new_customer_value"]
df.head()

Call  Failure  Complains  Subscription  Length  Charge  Amount  \
0              8          0                    38               0   
1              0          0                    39               0   
2             10          0                    37               0   
3             10          0                    38               0   
4              3          0                    38               0   

   Seconds of Use  Frequency of use  Frequency of SMS  \
0            4370                71                 5   
1             318                 5                 7   
2            2453                60               359   
3            4198                66                 1   
4            2393                58                 2   

   Distinct Called Numbers  Age Group  Tariff Plan  Status  Age  \
0                       17          3            1       1   30   
1                        4          2            1       2   25   
2                       24          3            1       1   30   
3                       35          1            1       1   15   
4                       33          1            1       1   15   

   Customer Value  Churn  
0         197.640      0  
1          46.035      0  
2        1536.520      0  
3         240.020      0  
4         145.805      0

## 7. Handling Missing Data

Real data often has missing values. pandas can find and fill (or drop) these empty spots easily.

**Uses**  
To clean data for analysis or machine learning.

In [288]:
df_with_nan = pd.DataFrame({'A': [1, None, 3], 'B': [4, 5, None]})
print(df_with_nan.fillna(0)) 
print(df_with_nan.dropna())   

     A    B
0  1.0  4.0
1  0.0  5.0
2  3.0  0.0
     A    B
0  1.0  4.0


## 8. Grouping and Aggregation

Grouping clusters your data by some value (like city or month), letting you calculate summaries for each group.

**Uses**  
To summarize, compare, or analyze trends by category.

In [291]:
scores = pd.DataFrame({'Team': ['A', 'B', 'A'], 'Points': [10, 20, 30]})
team_totals = scores.groupby('Team')['Points'].sum()
print(team_totals)

Team
A    40
B    20
Name: Points, dtype: int64


## 9. Sorting Data

pandas can arrange your table by values in any column, alphabetically or by size.

**Uses**  
To see the biggest, smallest, or otherwise organize your dataset.

In [294]:
df_sorted = df.sort_values('Seconds of Use', ascending=False)
df_sorted.head()

Call  Failure  Complains  Subscription  Length  Charge  Amount  \
2983             36          0                    34               5   
2583             34          0                    33               6   
883              31          1                    32               4   
483              29          0                    31               5   
2383             35          0                    39               5   

      Seconds of Use  Frequency of use  Frequency of SMS  \
2983           17090               255                15   
2583           16980               254                28   
883            16785               249                 8   
483            16675               248                21   
2383           16640               254                22   

      Distinct Called Numbers  Age Group  Tariff Plan  Status  Age  \
2983                       82          2            2       1   25   
2583                       97          2            2       1   25   
883                        80          2            1       1   25   
483                        95          2            1       1   25   
2383                       88          2            2       1   25   

      Customer Value  Churn  
2983         848.025      0  
2583         901.530      0  
883          802.530      0  
483          856.035      0  
2383         859.230      0

## 10. Merging and Joining DataFrames

You can combine two tables using a common column—just like matching student names to their grades.

**Uses**  
To combine more information from different sources, build larger analysis, or bring together related datasets.

In [297]:
data1 = pd.DataFrame({'ID': [1,2], 'Name': ['Anna', 'Bob']})
data2 = pd.DataFrame({'ID': [1,2], 'Score': [95, 88]})
merged = pd.merge(data1, data2, on='ID')
print(merged)

   ID  Name  Score
0   1  Anna     95
1   2   Bob     88


## 11. Applying Functions

pandas allows you to apply a function to every item or row in a column, making quick transformations or calculations.

**Uses**  
To process data flexibly, like formatting names or doing calculations.

In [300]:
df['Seconds of Use'] = df['Seconds of Use'].apply(lambda x: x / 1000000)
df.head()

Call  Failure  Complains  Subscription  Length  Charge  Amount  \
0              8          0                    38               0   
1              0          0                    39               0   
2             10          0                    37               0   
3             10          0                    38               0   
4              3          0                    38               0   

   Seconds of Use  Frequency of use  Frequency of SMS  \
0        0.004370                71                 5   
1        0.000318                 5                 7   
2        0.002453                60               359   
3        0.004198                66                 1   
4        0.002393                58                 2   

   Distinct Called Numbers  Age Group  Tariff Plan  Status  Age  \
0                       17          3            1       1   30   
1                        4          2            1       2   25   
2                       24          3            1       1   30   
3                       35          1            1       1   15   
4                       33          1            1       1   15   

   Customer Value  Churn  
0         197.640      0  
1          46.035      0  
2        1536.520      0  
3         240.020      0  
4         145.805      0

# 📘 Machine Learning Basic Notes

---

### 1. What is Machine Learning?
Machine Learning is a field of artificial intelligence that enables computers to learn patterns from data and make predictions or decisions without being explicitly programmed for each task.  
It focuses on building models that improve performance with experience, using algorithms that detect structure in data and generalize to unseen inputs.

---

### 2. Types of Machine Learning
- **Supervised Learning** learns from labeled data to predict outputs for new inputs.  
- **Unsupervised Learning** finds patterns or structure in unlabeled data, such as clustering or dimensionality reduction.  
- **Semi-supervised Learning** uses a mix of a small amount of labeled data and a large amount of unlabeled data to improve learning.  
- **Self-supervised Learning** creates pseudo-labels from the data itself to pretrain models.  
- **Reinforcement Learning** trains an agent to make sequential decisions by maximizing cumulative reward through interaction with an environment.

---

### 3. Supervised Learning: Regression vs Classification
- **Regression** predicts continuous numerical values, such as prices or temperatures, by modeling relationships between features and targets.  
- **Classification** predicts discrete categories or labels, such as spam vs not spam or disease presence vs absence, by learning decision boundaries separating classes.

---

### 4. Unsupervised Learning: Clustering and Dimensionality Reduction
- **Clustering** groups similar data points into clusters based on distance or similarity metrics, revealing hidden structure.  
- **Dimensionality Reduction** compresses high-dimensional data into fewer dimensions while preserving important information, improving efficiency, visualization, and model performance.

---

### 5. Feature Engineering
Feature Engineering is the process of transforming raw data into informative inputs for models.  
It includes handling missing values, encoding categorical variables, scaling numeric features, creating new features from domain knowledge, reducing dimensionality, and selecting relevant features to improve accuracy and generalization.

---

### 6. Train / Validation / Test Split
The dataset is split into:
- **Training data** for fitting the model  
- **Validation data** for tuning hyperparameters and preventing overfitting  
- **Test data** for unbiased evaluation  

Proper splitting ensures that performance metrics reflect real-world generalization and not memorization.

---

### 7. Overfitting and Underfitting
- **Overfitting** occurs when a model learns noise or details specific to the training data and performs poorly on new data.  
- **Underfitting** occurs when a model is too simple to capture the underlying patterns and performs poorly on both training and test data.  
- The goal is to achieve a **balance** that generalizes well.

---

### 8. Bias-Variance Tradeoff
- **Bias** measures error due to overly simplistic assumptions that miss true patterns.  
- **Variance** measures error due to sensitivity to fluctuations in the training data.  
Reducing bias often increases variance and vice versa.  
Effective modeling balances both to minimize total error and maximize generalization.

---

### 9. Evaluation Metrics for Regression
- **Mean Absolute Error (MAE)** → average absolute deviation  
- **Mean Squared Error (MSE)** → squared deviations  
- **Root Mean Squared Error (RMSE)** → square root of MSE, interpretable in original units  
- **R-squared (R²)** → proportion of variance explained by the model  

---

### 10. Evaluation Metrics for Classification
- **Accuracy** → overall correctness  
- **Precision** → correctness among predicted positives  
- **Recall** → coverage of actual positives  
- **F1-score** → harmonic mean of precision and recall  
- **ROC-AUC** → ranking quality across thresholds  
- **Confusion Matrix** → summarizes prediction outcomes  

---

### 11. Cross-Validation
Cross-Validation is a resampling strategy that splits data into multiple folds, training on subsets and validating on the remaining fold iteratively.  
- Produces more reliable estimates of model performance  
- Reduces variance due to a single split  
- Aids in model selection and hyperparameter tuning  

---

### 12. Data Preprocessing
Data Preprocessing prepares raw data for modeling by:
- Fixing inconsistent formats  
- Handling missing values  
- Scaling or normalizing features  
- Encoding categorical variables  
- Detecting outliers  
- Ensuring consistent schemas  

Good preprocessing improves model stability, speed, and predictive quality.

---

### 13. Scaling and Normalization
- **Scaling** transforms numeric features to a common range or distribution to stabilize optimization and distance-based computations.  
- **Standardization** → zero mean and unit variance  
- **Min-Max Scaling** → maps values to a fixed range  
- **Normalization** → scaling individual samples to unit norm  

---

### 14. Encoding Categorical Variables
- **One-Hot Encoding** → binary columns per category  
- **Ordinal Encoding** → maps ordered categories to integer ranks  
- **Target/Mean Encoding** → uses aggregated target statistics (requires careful leakage prevention)  

---

### 15. Handling Missing Data
- **Deletion** → when safe  
- **Simple Imputation** → constants, mean, median, mode  
- **Advanced Imputation** → model-based or iterative methods  

Proper handling prevents biased learning, preserves information, and maintains dataset integrity.

---

### 16. Outlier Detection
Outliers are unusual observations that deviate significantly from the majority of data.  
Detection methods include:
- Statistical thresholds  
- Robust distance metrics  
- Clustering-based detection  
- Isolation-based methods  

---

### 17. Model Selection
Model Selection compares candidate algorithms/configurations using validation procedures.  
Considers:
- Predictive accuracy  
- Interpretability  
- Computational efficiency  
- Data size  
- Deployment constraints  

---

### 18. Hyperparameters and Hyperparameter Tuning
- **Hyperparameters** control model behavior and learning process but are not learned directly from data.  
- **Tuning methods**:
  - Grid Search  
  - Random Search  
  - Bayesian Optimization  

---

### 19. Regularization
Adds constraints or penalties to model parameters to prevent overfitting.  
- **L1 Regularization** → sparsity  
- **L2 Regularization** → discourages large weights  
- **Elastic Net** → combination of L1 + L2  
- **Neural Networks** → dropout, early stopping  

---

### 20. Linear Regression
- Models a linear relationship between features and a continuous target by minimizing a loss function.  
- Provides interpretable coefficients.  
- May require scaling and regularization in high-dimensional settings.  

---

### 21. Logistic Regression
- Classification algorithm that models the probability of a class using a logistic function.  
- Outputs probabilities and decision thresholds.  
- Supports regularization, robust and interpretable.  

---

### 22. k-Nearest Neighbors (KNN)
- Nonparametric method that classifies/regresses based on nearest neighbors.  
- Relies on distance metrics, benefits from scaling.  
- Captures complex boundaries but computationally expensive at prediction.  

---

### 23. Decision Trees
- Splits feature space into regions using simple decision rules.  
- Handles nonlinear relationships, mixed data types.  
- Interpretable, minimal preprocessing.  
- Risk of overfitting without pruning/constraints.  

---

### 24. Random Forests
- Ensembles of decision trees trained on bootstrapped samples + random feature subsets.  
- Improves generalization by averaging predictions.  
- Reduces variance, provides feature importance.  

---

### 25. Gradient Boosting
- Sequentially builds weak learners, each correcting previous errors.  
- Optimizes a loss function.  
- Achieves high accuracy with proper regularization, learning rate control, and early stopping.  

---

### 26. XGBoost, LightGBM, and CatBoost
- Optimized gradient boosting frameworks.  
- Efficient training, advanced regularization.  
- Handle categorical features, parallelization, monotonic constraints.  
- Often yield state-of-the-art results.  

---

### 27. Support Vector Machines (SVM)
- Finds decision boundary with maximum margin between classes.  
- Uses kernels for nonlinear problems.  
- Effective in high-dimensional spaces, requires scaling.  
- Sensitive to hyperparameters/kernel choice.  

---

### 28. Naive Bayes
- Probabilistic classifier (Bayes’ theorem, independence assumption).  
- Simple, fast, effective for text classification.  
- Assumption limits accuracy when features are correlated.  

---

### 29. Neural Networks and Deep Learning
- Layered function approximators that learn complex patterns.  
- Deep Learning → multiple layers capturing hierarchical representations.  
- Enabled breakthroughs in vision, NLP, speech.  

---

### 30. Activation Functions
Introduce nonlinearity into neural networks:
- **ReLU** → efficient, sparse activation  
- **Sigmoid** → bounded outputs  
- **Tanh** → centered outputs  

Choice affects gradient flow and learning.

---

### 31. Loss Functions
- **Regression** → Mean Squared Error, Mean Absolute Error  
- **Classification** → Cross-entropy  
- **Margin-based** → Hinge loss  

Proper choice aligns training with evaluation goals.

---

### 32. Optimization and Gradient Descent
Optimization algorithms adjust model parameters to minimize loss.  
- **Gradient Descent** iteratively updates parameters.  
- Variants:
  - Stochastic Gradient Descent (SGD)  
  - Mini-batch GD  
  - Momentum  
  - RMSProp  
  - Adam  

---

### 33. Regularization in Neural Networks
Techniques include:
- **L2 Weight Decay**  
- **Dropout** → randomly deactivate units  
- **Batch Normalization**  
- **Data Augmentation**  
- **Early Stopping**  

---

### 34. Model Interpretability
Provides insight into how models make predictions.  
Techniques:
- Feature importance  
- Partial dependence plots  
- SHAP values  
- LIME  

Interpretability supports trust, debugging, compliance, and responsible deployment.

---

### 35. Imbalanced Data Handling
- Occurs when classes are unequally represented.  
- Strategies:
  - Resampling  
  - Synthetic data generation (SMOTE)  
  - Class weighting  
  - Threshold tuning  
- Metrics: Recall, F1, AUC-PR (better than accuracy).  

---
